dev:
  extends:
    service: hello_world_python
    file: ../../docker-compose.yml
  volumes:
    - ./:/opt/services/hello-world-python

prod:
  image: 394389787758.dkr.ecr.us-east-1.amazonaws.com/devbox/hello_world_python:latest
  container_name: hello_world_python
  hostname: hello_world_python
  ports:
    - '5000'
  env_file:
    - .env-example
